
# Reading and Operating this file
# ~ is basically Null/None/False e.t.c, you can either use ~ as the value, or comment out the line
# A commented-out line's value is typically it's default but is disabled due to it being commented out
# When a line starts with two #'s (comment line starting with #), then when un-commenting, it's intended to be disabled
# for example, under network_G everything but ESRGAN's values are commented-out, so to show which should still be
# enabled/disabled, a double-comment is used

name: debug_003_SFTGANx4_OST  # put "debug" in the name to enable debug mode, only enable to test code works!!!
use_tb_logger: false
model: sftgan
scale: 4
gpu_ids:
- 0
datasets:
  train:
    name: OST
    mode: LRHRseg_bg
    dataroot_HR: /mnt/SSD/xtwang/BasicSR_datasets/OST/train/img
    dataroot_HR_bg: /mnt/SSD/xtwang/BasicSR_datasets/DIV2K800/DIV2K800_sub
    dataroot_LR: ~
    subset_file: ~
    use_shuffle: true
    n_workers: 8
    batch_size: 16
    HR_size: 96
    use_flip: true
    use_rot: false
  val:
    name: val_OST300_part
    mode: LRHRseg_bg
    dataroot_HR: /mnt/SSD/xtwang/BasicSR_datasets/OST/val/img
    dataroot_LR: ~
path:
  root: /home/xtwang/Projects/BasicSR
  resume_state: ~
  pretrain_model_G: ../experiments/pretrained_models/sft_net_ini.pth
network_G:
  which_model_G: sft_arch
network_D:
  which_model_D: dis_acd
train:
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  lr_scheme: MultiStepLR
  lr_steps:
  - 50000
  - 100000
  - 150000
  - 200000
  lr_gamma: 0.5
  pixel_criterion: l1
  pixel_weight: 0
  feature_criterion: l1
  feature_weight: 1
  gan_type: vanilla
  gan_weight: !!float 5e-3

  # for wgan-gp
  #D_update_ratio: 1
  #D_init_iters: 0
  #gp_weigth: 10
  manual_seed: 0
  niter: !!float 6e5
  val_freq: !!float 2e3
logger:
  print_freq: 200,
  save_checkpoint_freq: !!float 2e3